#!/bin/bash
printf "Вы воспользовались инсталлером Ds(@e52699v4) \n\n\n\n" 
REPO_URL="https://github.com/ElectroZybr/Chemical-simulator.git" 
DIR_NAME="Chemical-simulator" 

show_help() {
    printf " | флаг | расшифровка           | действие                                                 | \n" 
    printf " | -i   | &installer            | Установить (с нуля)                                      | \n"
    printf " | -u   | &update               | Обновить (обычный git pull)                              | \n"
    printf " | -ip  | &installer pull --d1  | Быстрое обновление (git pull --depth 1)                  | \n"
    printf " | -it  | &installer #teg       | Установить конкретную версию по ТЕГУ                     | \n"
    printf " | -ich | &installer comit hesh | Установить по хешу КОММИТА                               | \n"
    printf " | -ri  | &reinstall            | Переустановить (удалить старое и скачать заново)         | \n"
    printf " | -d   | &delete (all)         | Полное удаление скрипта и проекта                        | \n"
    printf " | -dp  | &delete projekt       | Удаление только проекта                                  | \n"
    printf " | -icl | &installer clean      | Скачивание проекта без компиляции                        | \n"
    printf " | -ic  | &installer clone      | Скачивание только нужных файлов и сборка (--depth 1)     | \n"
    printf " | -t   | &test                 | Создает тестовую папку для экспериментов                 | \n"
}

build_logic() {
    cmake -S . -B build && cmake --build build
    cp build/Chemical-simulator .
    printf "Операция завершена. \n"
}

if [ -z "$1" ]; then
    show_help
    exit 1
fi

case "$1" in
    -i)
        if [ -d "$DIR_NAME" ]; then 
            printf "Ошибка: Папка $DIR_NAME уже существует. \n"
        else
            git clone "$REPO_URL"
            cd "$DIR_NAME" || exit
            build_logic
        fi
        ;;
    -u)
        if [ -d "$DIR_NAME" ]; then 
            cd "$DIR_NAME" || exit
            git pull
            build_logic
        else
            printf "Ошибка: Проект не найден. \n"
        fi
        ;;
    -ip)
        if [ -d "$DIR_NAME" ]; then 
            cd "$DIR_NAME" || exit
            git pull --depth 1
            build_logic
        else
            printf "Ошибка: Проект не найден. \n"
        fi
        ;;
    -it)
        git clone "$REPO_URL"
        cd "$DIR_NAME" || exit
        printf "Доступные теги (версии): \n"
        git tag
        read -p "Введите имя тега: " USER_TAG
        git checkout "$USER_TAG"
        build_logic
        ;;
    -ich)
        git clone "$REPO_URL"
        cd "$DIR_NAME" || exit
        printf "Последние коммиты: \n"
        git log --oneline -n 10
        read -p "Введите хеш коммита: " USER_COMMIT
        git checkout "$USER_COMMIT"
        build_logic
        ;;
    -ri)
        rm -rf "$DIR_NAME"
        git clone "$REPO_URL" && cd "$DIR_NAME" && build_logic
        ;;
    -d)
        rm -rf "$DIR_NAME"
        printf "Удаление завершено. \n"
        rm -- "$0"
        ;;
    -dp)
        rm -rf "$DIR_NAME"
        ;;
    -icl)
        git clone "$REPO_URL"
        cd "$DIR_NAME" && ls -F && du -sh .
        ;;
    -ic)
        git clone --depth 1 "$REPO_URL"
        cd "$DIR_NAME" || exit
        build_logic
        ;;
    -t)
        mkdir "$DIR_NAME"
        printf "Тестовая папка создана. \n"
        ;;
    *)
        show_help
        ;;
esac